# Generated by Django 6.0 on 2025-12-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='currence',
            new_name='currency',
        ),
    ]
